

ALTER TABLE invoice_items
  ADD COLUMN IF NOT EXISTS "cgstAmount" decimal(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sgstAmount" decimal(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "igstAmount" decimal(10,2) NOT NULL DEFAULT 0;
